branches:
  only:
    - master

before_install:
  - sudo add-apt-repository -y ppa:texlive-backports # TexLive
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y --force-yes --no-install-recommends texlive-base texlive-latex-recommended texlive-latex-extra lmodern
  
script: pdflatex -interaction=nonstopmode Rapport.tex
